services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_mqtt && rabbitmq-server"
    volumes:
        #- ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/var/lib/rabbitmq
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    depends_on:
      - rabbitmq
      - minio
    volumes:
      - ./nodered_data:/data

  python-app:
    build: ./app
    image: vasilhspii/python-app:1.0
    container_name: python-app
    depends_on:
      - rabbitmq
      - minio

  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.0"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1884:1883"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: ${TB_SERVICE_ID}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    depends_on:
      - postgres
    volumes:
      - ./thingsboard_data:/data 

volumes:
  minio_data:
  rabbitmq_data:
  nodered_data:
  postgres-data:
    name: tb-postgres-data
    driver: local
