# app/Dockerfile
FROM python:3.11

# Set workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Run script
CMD ["python", "main.py"]
